pipeline {
    agent{
        node {
            label 'docker-agent-alpine'
        }
    }
    environment {
        PROJECT_DIR = 'src/Entregable_2/Code'
    }
    stages {
        stage('Build') {
            steps {
                echo "Compilando el proyecto..."
                sh """
                cd ${PROJECT_DIR}
                javac -d out \$(find . -name "*.java")
                """
            }
        }
        stage('Javadoc') {
            steps {
                echo "Generando Javadoc..."
                sh """
                javadoc -d src/Entregable_2/docs -sourcepath src -subpackages Entregable_2.Code
                """
            }
        }
        stage('Commit Javadoc') {
            steps {
                echo "Actualizando el repositorio con la documentación generada..."
                sh """
                git config --global user.email "jenkins@example.com"
                git config --global user.name "Jenkins"
                cd src/Entregable_2
                git add docs
                git commit -m "Actualización de Javadoc"
                git push origin main
                """
            }
        }
    }
    post {
        always {
            echo "Pipeline finalizado."
            cleanWs()
        }
        failure {
            echo "Pipeline falló. Verifica los errores."
        }
        success {
            echo "Pipeline ejecutado exitosamente."
        }
    }
}
