import ply.lex as lex

# Definir tokens
tokens = (
    'TRAEME', 'TODO', 'DE_LA_TABLA', 'DONDE', 'AGRUPANDO_POR', 'MEZCLANDO', 'EN', 'LOS_DISTINTOS', 
    'CONTANDO', 'METE_EN', 'LOS_VALORES', 'ACTUALIZA', 'SETEA', 'BORRA_DE_LA', 'ORDENA_POR', 
    'COMO_MUCHO', 'WHERE_DEL_GROUP_BY', 'EXISTE', 'EN_ESTO', 'ENTRE', 'PARECIDO_A', 'ES_NULO',
    'CAMBIA_LA_TABLA', 'AGREGA_LA_COLUMNA', 'ELIMINA_LA_COLUMNA', 'CREA_LA_TABLA', 'TIRA_LA_TABLA', 
    'POR_DEFECTO', 'UNICO', 'CLAVE_PRIMA', 'CLAVE_REFERENTE', 'NO_NULO', 'TRANSFORMA_A',
)

# Reglas léxicas
t_TRAEME = r'TRAEME'
t_TODO = r'TODO'
t_DE_LA_TABLA = r'DE LA TABLA'
t_DONDE = r'DONDE'
t_AGRUPANDO_POR = r'AGRUPANDO POR'
t_MEZCLANDO = r'MEZCLANDO'
t_EN = r'EN'
t_LOS_DISTINTOS = r'LOS DISTINTOS'
t_CONTANDO = r'CONTANDO'
t_METE_EN = r'METE EN'
t_LOS_VALORES = r'LOS VALORES'
t_ACTUALIZA = r'ACTUALIZA'
t_SETEA = r'SETEA'
t_BORRA_DE_LA = r'BORRA DE LA'
t_ORDENA_POR = r'ORDENA POR'
t_COMO_MUCHO = r'COMO MUCHO'
t_WHERE_DEL_GROUP_BY = r'WHERE DEL GROUP BY'
t_EXISTE = r'EXISTE'
t_EN_ESTO = r'EN ESTO:'
t_ENTRE = r'ENTRE'
t_PARECIDO_A = r'PARECIDO A'
t_ES_NULO = r'ES NULO'
t_CAMBIA_LA_TABLA = r'CAMBIA LA TABLA'
t_AGREGA_LA_COLUMNA = r'AGREGA LA COLUMNA'
t_ELIMINA_LA_COLUMNA = r'ELIMINA LA COLUMNA'
t_CREA_LA_TABLA = r'CREA LA TABLA'
t_TIRA_LA_TABLA = r'TIRA LA TABLA'
t_POR_DEFECTO = r'POR DEFECTO'
t_UNICO = r'UNICO'
t_CLAVE_PRIMA = r'CLAVE PRIMA'
t_CLAVE_REFERENTE = r'CLAVE REFERENTE'
t_NO_NULO = r'NO NULO'
t_TRANSFORMA_A = r'TRANSFORMA A'

# Otras reglas necesarias (identificadores, números, operadores, etc.)
t_ignore = ' \t'

def t_error(t):
    print(f"Token no reconocido: {t.value[0]}")
    t.lexer.skip(1)

# Crear lexer
lexer = lex.lex()
