pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "Compilando el proyecto de Python..."
                sh """
                cd src/Entregable_3
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                """
            }
        }
        
        stage('PyDocs') {
            steps {
                echo "Generando documentación PyDoc del módulo..."
                sh """
                cd src/Entregable_3
                # Crear los archivos HTML de la documentación directamente en el directorio 'docs'
                mkdir -p docs
                find . -name "*.py" ! -name "__init__.py" -exec python -m pydoc {} \; -exec sh -c 'mv {} docs/$(basename {} .py).html'
                """
            }
        }
    }
}
