pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "Compilando el proyecto de Python..."
                sh """
                cd src/Entregable_3
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                """
            }
        }
        
        stage('PyDocs-Pedidos') {
    steps {
        echo "Generando documentación PyDoc..."
        sh """
        # Asegurarse de estar en el directorio correcto
        cd src/Entregable_3

        # Usar bash para ejecutar el comando sin problemas con el shell
        bash -c "mkdir -p docs && find . -name '*.py' ! -name '__init__.py' -exec python -m pydoc {} > docs/$(basename {} .py).html \;"
        """
    }
}

    }
}
